# WARNING - Generated by {fusen} from dev/flat_function.Rmd: do not edit by hand

test_that("get_one_file_size fonctionne correctement pour un fichier existant", {
  mon_dossier_temp_aleatoire <- tempfile(pattern = "toto")
  dir.create(mon_dossier_temp_aleatoire)
  temp_file <- tempfile("example_", tmpdir = mon_dossier_temp_aleatoire, fileext = ".txt")
    writeLines("Ceci est un fichier temporaire pour tester la fonction get_one_file_size.", temp_file)
  expected_size <- file.size(temp_file)
  result <- get_one_file_size(temp_file)
  expect_true(is.data.frame(result))
  expect_equal(ncol(result), 2)
  expect_equal(names(result), c("filename", "size"))
  expect_equal(result$filename, temp_file)
  expect_equal(result$size, expected_size)
  unlink(temp_file)
  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
})
