# WARNING - Generated by {fusen} from dev/flat_function.Rmd: do not edit by hand

#' function get_one_file_size
#'
#' @param filename un nom de fichier
#'
#' @return dataframe un dateframe contenant le nom du fichier et sa taille
#' @export
#'
#' @examples

#' mon_dossier_temp_aleatoire <- tempfile(pattern = "toto")
#' dir.create(mon_dossier_temp_aleatoire)
#' un_fichier <- file.path(mon_dossier_temp_aleatoire, "monfichier.csv")
#' get_one_file_size(un_fichier)
get_one_file_size <- function(filename) {
  file_size <- file.size(filename)
  result <- data.frame(
    filename = filename,
    size = file_size,
    stringsAsFactors = FALSE
  )
  return(result)
}
